// POST   /music/songs
// GET    /music/songs
// DELETE /music/songs/:songId
// POST   /music/rooms
// POST   /music/rooms/join/:token
// POST   /music/rooms/:roomId/leave
// POST   /music/rooms/:roomId/control
// POST   /music/rooms/:roomId/request
// PUT    /music/rooms/:roomId/request/:requestId
// GET    /music/rooms/:token
