// getProfile(userId)
// updateProfile(userId, data)
// blockUser(userId, targetId)
// unblockUser(userId, targetId)
// muteUser(userId, targetId)
// setGhostMode(userId, options)
// claimDailyCoins(userId)
// getLeaderboard()
// getTransactionHistory(userId)
