// POST   /groups
// GET    /groups/:groupId
// PUT    /groups/:groupId
// POST   /groups/:groupId/members
// DELETE /groups/:groupId/members/:userId
// POST   /groups/:groupId/admins/:userId
// DELETE /groups/:groupId/admins/:userId
// POST   /groups/:groupId/leave
// POST   /groups/:groupId/report
// PUT    /groups/:groupId/sleep-mode
