// POST   /chat/:chatId/messages
// GET    /chat/:chatId/messages
// DELETE /chat/messages/:messageId/everyone
// DELETE /chat/messages/:messageId/me
// POST   /chat/messages/:messageId/forward
// POST   /chat/:chatId/pin/:messageId
// DELETE /chat/:chatId/pin/:messageId
// POST   /chat/:chatId/read
// POST   /chat/direct/:targetId
// GET    /chat/:chatId/search
// GET    /chat/:chatId/throwback
